# Generated by Django 3.2.14 on 2022-07-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Fake'), (1, 'Fact')]),
        ),
    ]
